"""
email_alert.py - SMTP email alert sender (Gmail App Password compatible).
Only sends when a real attack is detected.
"""

import smtplib
import threading
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

# ── Configure these before running ─────────────────────────────────────────
SMTP_HOST     = "smtp.gmail.com"
SMTP_PORT     = 587
SENDER_EMAIL  = "anandsharma7477@gmail.com"       # ← replace
SENDER_PASS   = "uarymuwtruivxskq"          # ← replace (Gmail App Password)
RECIPIENT     = "anandsharma7477@gmail.com"  # ← replace
EMAIL_ENABLED = True  # Set to True once credentials are filled in


def _send(subject: str, body: str):
    """Internal blocking send — called in a thread so UI never blocks."""
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = SENDER_EMAIL
        msg["To"]      = RECIPIENT

        html = f"""
        <html><body style="font-family:monospace;background:#0d1117;color:#00ff99;padding:20px;">
        <h2 style="color:#ff4b4b;">🚨 IDS ALERT — {subject}</h2>
        <pre style="background:#161b22;padding:16px;border-radius:8px;color:#e6edf3;">{body}</pre>
        <p style="color:#8b949e;font-size:12px;">Generated by NetGuard IDS &middot; {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </body></html>
        """
        msg.attach(MIMEText(body, "plain"))
        msg.attach(MIMEText(html, "html"))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SENDER_EMAIL, SENDER_PASS)
            server.sendmail(SENDER_EMAIL, RECIPIENT, msg.as_string())
    except Exception as e:
        print(f"[EmailAlert] Failed to send: {e}")


def send_alert(attack_type: str, src_ip: str, domain: str = "Unknown", dst_port: int = 0):
    """Non-blocking alert dispatch."""
    if not EMAIL_ENABLED:
        return
    subject = f"Attack Detected: {attack_type}"
    body = (
        f"Attack Type : {attack_type}\n"
        f"Attacker IP : {src_ip}\n"
        f"Domain      : {domain}\n"
        f"Target Port : {dst_port}\n"
        f"Time        : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    )
    threading.Thread(target=_send, args=(subject, body), daemon=True).start()
